### ISSUE TITLE
[Tracking issue] Upstream

### ISSUE THREAD

**Issue by kassane** [kassane/zig-mos-bootstrap#1]
## See

- [ ] https://github.com/ziglang/zig/issues/6502
- [ ] https://github.com/llvm-mos/llvm-mos/issues/422
- [ ] https://github.com/llvm-mos/llvm-mos/pull/310
- [ ] https://github.com/llvm-mos/llvm-mos/issues/191
- [ ] https://github.com/llvm-mos/llvm-mos/issues/423
- [ ] https://github.com/llvm-mos/llvm-mos-sdk/issues/102
- [ ] https://github.com/llvm-mos/llvm-mos-sdk/issues/205
